
package com.study.webservice.cxf.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.10
 * Fri Dec 01 16:48:37 CST 2017
 * Generated source version: 2.0.10
 * 
 */

@WebService(targetNamespace = "http://intf.server.cxf.webservice.study.com/", name = "HelloWorld")

public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://intf.server.cxf.webservice.study.com/", className = "com.study.webservice.cxf.sei.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://intf.server.cxf.webservice.study.com/", className = "com.study.webservice.cxf.sei.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
